### ISSUE TITLE
Ionic 2?

### ISSUE THREAD

**Issue by ghost** [dpramar/ionic-tabs-starter-sass-jade-coffee#3]
Is there any way to use Ionic 2 here instead? I am not sure exactly how to replace it. It would be great if you could suggest some method! The difficulty not only lies in the Ionic part, but also how to put the compiled-from-CoffeeScript JavaScript into Babel so we can use ES6 stuff like `import {something} from something`.

**Comment by dpramar** [comment]
Ionic 2 is still in beta, but if you want to change the ionic version you should update the bower dependency https://github.com/dpramar/ionic-tabs-starter-sass-jade-coffee/blob/master/bower.json#L5

About CoffeeScrip and ES6, it's not possible because CoffeeScript doesn't understand that syntax, therefore the compilation will fail. So, unless coffeescript accepts ES6 syntax you won't be able use it.
